env:
    global:
        # Package name
        - PACKAGE="UnitTesting-example"

# mutliple os matrix
# https://docs.travis-ci.com/user/multi-os/#Python-example-(unsupported-languages)
matrix:
    include:
        - os: linux
          language: python
          env: SUBLIME_TEXT_VERSION="2"
        - os: linux
          language: python
          env: SUBLIME_TEXT_VERSION="3"
        - os: osx
          language: generic
          env: SUBLIME_TEXT_VERSION="2"
        - os: osx
          language: generic
          env: SUBLIME_TEXT_VERSION="3"

before_install:
    - curl -OL https://raw.githubusercontent.com/randy3k/UnitTesting/master/sbin/travis.sh
    # enable gui, see https://docs.travis-ci.com/user/gui-and-headless-browsers
    - if [ "$TRAVIS_OS_NAME" == "linux"  ]; then
            export DISPLAY=:99.0;
            sh -e /etc/init.d/xvfb start;
      fi

install:
    # bootstrap the testing environment
    - sh travis.sh bootstrap
    # install Package Control and package denepdencies
    # - sh travis.sh install_package_control

script:
    # run tests with test coverage report
    - sh travis.sh run_tests --coverage
    # run tests without test coverage report
    # - sh travis.sh run_tests
    # testing syntax_test files
    # - sh travis.sh run_syntax_tests

after_success:
    # remove the following if `coveralls` is not needed
    - if [ "$SUBLIME_TEXT_VERSION" == "3" ] && [ "$TRAVIS_OS_NAME" == "osx" ]; then
            brew update;
            brew install python;
      fi
    - if [ "$SUBLIME_TEXT_VERSION" == "3" ]; then
            pip install coveralls;
            coveralls;
      fi

notifications:
    email: false
