os:
    - linux
    - osx

sudo: required

env:
    global:
        # The package name
        - PACKAGE="UnitTesting-example"
    matrix:
        - SUBLIME_TEXT_VERSION="2"
        - SUBLIME_TEXT_VERSION="3"

before_install:
    - curl -OL https://raw.githubusercontent.com/randy3k/UnitTesting/master/sbin/travis.sh
    # enable gui, see https://docs.travis-ci.com/user/gui-and-headless-browsers
    - if [ "$TRAVIS_OS_NAME" == "linux"  ]; then
            export DISPLAY=:99.0;
            sh -e /etc/init.d/xvfb start;
      fi

install:
    # bootstrap the testing environment
    - sh travis.sh bootstrap
    # install Package Control and package denepdencies
    # - sh travis.sh install_package_control

script:
    # run tests with test coverage report
    - sh travis.sh run_tests --coverage
    # run tests without test coverage report
    # - sh travis.sh run_tests
    # testing syntax_test files
    # - sh travis.sh run_syntax_tests

after_success:
    # remove this line if don't need coveralls
    - if [ "$SUBLIME_TEXT_VERSION" == "3" ]; then
            sudo pip install python-coveralls;
            coveralls;
      fi

notifications:
    email: false
