os:
    - linux
    - osx

sudo: required

env:
    global:
        # Your package name
        - PACKAGE="UnitTesting-example"
    matrix:
        - SUBLIME_TEXT_VERSION="2"
        - SUBLIME_TEXT_VERSION="3"

before_install:
    - curl -OL https://raw.githubusercontent.com/randy3k/UnitTesting/master/sbin/travis.sh
    - if [ "$TRAVIS_OS_NAME" == "linux"  ]; then
            export DISPLAY=:99.0;
            sh -e /etc/init.d/xvfb start;
      fi

install:
    - sh travis.sh bootstrap

script:
    - sh travis.sh run_syntax_tests

notifications:
    email: false
