env:
    global:
        - PACKAGE="UnitTesting-example" # Package name
        - SUBLIME_TEXT_VERSION="3"
        # use UNITTESTING_TAG to specific tag of UnitTesting
        # - UNITTESTING_TAG="master"

# mutliple os matrix
# https://docs.travis-ci.com/user/multi-os/#Python-example-(unsupported-languages)
matrix:
    include:
        - os: linux
          language: python
        - os: osx
          language: generic

services:
    - xvfb

before_install:
    - curl -OL https://raw.githubusercontent.com/SublimeText/UnitTesting/master/sbin/travis.sh

install:
    # bootstrap the testing environment
    - sh travis.sh bootstrap
    # install Package Control and package denepdencies
    # - sh travis.sh install_package_control

script:
    # run tests with test coverage report
    - sh travis.sh run_tests --coverage
    # testing syntax_test files
    # - sh travis.sh run_syntax_tests
    # - sh travis.sh run_syntax_compatibility

after_success:
    # remove the following if `coveralls` is not needed
    - pip3 install python-coveralls;
    - pip3 install codecov;
    - coveralls
    - codecov

notifications:
    email: false
